'use strict';

/**
 * Central config — every env-var read happens here.
 * server.js and route files import from this module.
 */

// Load .env if present (dev convenience; in production set env vars directly)
try {
  require('dotenv').config();
} catch (_) {
  // dotenv is optional — ignore if not installed
}

// ── Required secrets ────────────────────────────────────────────────────────
const JWT_SECRET = process.env.JWT_SECRET;
if (!JWT_SECRET) {
  console.error('[config] FATAL: JWT_SECRET env var is not set. Refusing to start.');
  process.exit(1);
}

// ── User store ──────────────────────────────────────────────────────────────
// Users are defined as  USER_<NAME>=<bcrypt-hash>  in the environment.
// Example .env line (generated by scripts/add-user.js):
//   USER_ojash=$2b$10$...
//
// Username matching is case-insensitive.
function loadUsers() {
  const users = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (key.startsWith('USER_')) {
      const username = key.slice(5).toLowerCase();
      users[username] = value; // value is the bcrypt hash
    }
  }
  return users;
}

module.exports = {
  PORT:      parseInt(process.env.PORT      || '3000', 10),
  FLASK_URL: process.env.FLASK_URL           || 'http://localhost:5000',
  IS_PROD:   process.env.NODE_ENV            === 'production',
  JWT_SECRET,
  JWT_EXPIRY: process.env.JWT_EXPIRY         || '8h',
  loadUsers,
};
