name: Deploy RTI-RAG

on:
  push:
    branches:
      - citizen-facing

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to VM
        run: |
            /home/cmit/project/deploy-rti-rag.sh